import type { PublicReview, ReviewSummary } from "./PublicReviewsList";

export const mockReviews: PublicReview[] = [
  {
    id: "1",
    rating: 5,
    category: "product",
    review_text: "พอดใหม่มาก รสชาติดีมากๆ ใช้มา 3 วันแล้วยังไม่มีปัญหาเลย ของแท้แน่นอน",
    published_at: "2026-09-08T14:30:00Z",
    masked_order_number: "POD-****-7821",
    masked_customer_name: "สมศักดิ์ พ.",
    verification_status: "delivered",
    items: [{ product_name: "Relx Infinity 2", flavor_name: "Dark Sorbet", brand_name: "RELX" }],
  },
  {
    id: "2",
    rating: 5,
    category: "delivery",
    review_text: "จัดส่งเร็วมาก สั่งวันนี้พรุ่งนี้ถึง แพ็คอย่างดี ไม่ชำรุด ประทับใจมากครับ",
    published_at: "2026-09-07T09:15:00Z",
    masked_order_number: "POD-****-3156",
    masked_customer_name: "ณัฐพงษ์ ส.",
    verification_status: "delivered",
    items: [{ product_name: "SKE Crystal Bar", flavor_name: "Blue Fusion", brand_name: "SKE" }],
  },
  {
    id: "3",
    rating: 4,
    category: "service",
    review_text: "ระบบใช้งานง่าย ชำระเงินสะดวก แต่หวังว่าจะมีสินค้าเพิ่มเติมในอนาคต",
    published_at: "2026-09-06T16:45:00Z",
    masked_order_number: "POD-****-9024",
    masked_customer_name: "วิภา ท.",
    verification_status: "payment_confirmed",
    items: [{ product_name: "Kardinal Stick", flavor_name: "Lush Ice", brand_name: "KARDINAL" }],
  },
  {
    id: "4",
    rating: 5,
    category: "overall",
    review_text: "บริการดีมาก ติดตามออเดอร์ได้ชัดเจน สินค้าคุณภาพเยี่ยม จะซื้อซ้ำแน่นอน",
    published_at: "2026-09-05T11:20:00Z",
    masked_order_number: "POD-****-4532",
    masked_customer_name: "ภัทรพล ก.",
    verification_status: "delivered",
    items: [
      { product_name: "SP2S Device", flavor_name: "Cigarette Tobacco", brand_name: "SP2S" },
      { product_name: "SP2S Pod", flavor_name: "Ice Mint", brand_name: "SP2S" },
    ],
  },
  {
    id: "5",
    rating: 5,
    category: "product",
    review_text: "รส Menthol สดชื่นมาก ไม่แสบคอ ดึงได้ลื่น คุ้มค่ามากๆ",
    published_at: "2026-09-04T18:30:00Z",
    masked_order_number: "POD-****-8871",
    masked_customer_name: "เมธา จ.",
    verification_status: "shipped",
    items: [{ product_name: "Relx Pod Pro", flavor_name: "Zesty Menthol", brand_name: "RELX" }],
  },
  {
    id: "6",
    rating: 4,
    category: "delivery",
    review_text: "ได้รับสินค้าตรงเวลา แพ็คกิ่งแน่นหนา แต่ต้องรอนานหน่อยเพราะสั่งช่วงเทศกาล",
    published_at: "2026-09-03T13:00:00Z",
    masked_order_number: "POD-****-2265",
    masked_customer_name: "นิภา ร.",
    verification_status: "delivered",
    items: [{ product_name: "Infy Pod", flavor_name: "Lychee Ice", brand_name: "INFY" }],
  },
  {
    id: "7",
    rating: 5,
    category: "service",
    review_text: "แอดมินตอบไวมาก มีปัญหาอะไรสอบถามแล้วช่วยแก้ไขทันที ขอบคุณค่ะ",
    published_at: "2026-09-02T10:45:00Z",
    masked_order_number: "POD-****-6743",
    masked_customer_name: "ประภาพร น.",
    verification_status: "delivered",
    items: [{ product_name: "Jues Pod", flavor_name: "Grape Ice", brand_name: "JUES" }],
  },
  {
    id: "8",
    rating: 5,
    category: "overall",
    review_text: "ร้านนี้ดีที่สุดเลยครับ สินค้าแท้ ราคาดี จัดส่งเร็ว ไม่ต้องหาที่อื่นแล้ว",
    published_at: "2026-09-01T15:20:00Z",
    masked_order_number: "POD-****-5189",
    masked_customer_name: "สุชาติ ว.",
    verification_status: "delivered",
    items: [
      { product_name: "Relx Infinity 2", flavor_name: "Bright Tobacco", brand_name: "RELX" },
      { product_name: "Relx Pod Pro", flavor_name: "Watermelon", brand_name: "RELX" },
    ],
  },
  {
    id: "9",
    rating: 4,
    category: "product",
    review_text: "พอดรสผลไม้หอมมาก แต่ใช้ไปสักพักเริ่มจืดหน่อย อาจต้องเปลี่ยนบ่อยขึ้น",
    published_at: "2026-08-31T08:50:00Z",
    masked_order_number: "POD-****-3342",
    masked_customer_name: "อรุณี ท.",
    verification_status: "delivered",
    items: [{ product_name: "Kardinal Stick", flavor_name: "Mango Freeze", brand_name: "KARDINAL" }],
  },
  {
    id: "10",
    rating: 5,
    category: "delivery",
    review_text: "ส่งถึงมือภายใน 24 ชั่วโมง แพ็คห่อดีมาก มีฟองน้ำป้องกันกระแทก เห็นใจลูกค้ามาก",
    published_at: "2026-08-30T12:10:00Z",
    masked_order_number: "POD-****-7654",
    masked_customer_name: "ภูมิพงษ์ ค.",
    verification_status: "delivered",
    items: [{ product_name: "SP2S Device", flavor_name: "Classic Tobacco", brand_name: "SP2S" }],
  },
];

export const mockReviewSummary: ReviewSummary = {
  average_rating: 4.7,
  total_reviews: 10,
  rating_distribution: { 1: 0, 2: 0, 3: 0, 4: 3, 5: 7 },
};

export const mockReviewsPreviewData = {
  reviews: mockReviews,
  summary: mockReviewSummary,
};