import type { PublicReview, ReviewSummary } from "./PublicReviewsList";

export const mockReviews: PublicReview[] = [
  {
    id: "1",
    rating: 5,
    category: "product",
    review_text: "พอดใหม่มาก รสชาติดีมากๆ ใช้มา 3 วันแล้วยังไม่มีปัญหาเลย ของแท้แน่นอน",
    published_at: "2026-09-08T14:30:00Z",
    masked_order_number: "POD-****-7821",
    masked_customer_name: "บอม พ.",
    verification_status: "delivered",
    items: [{ product_name: "MARBO M SWITCH 15K", flavor_name: "Grape Lychee", brand_name: "MARBO" }],
  },
  {
    id: "2",
    rating: 5,
    category: "delivery",
    review_text: "จัดส่งเร็วมาก สั่งวันนี้พรุ่งนี้ถึง แพ็คอย่างดี ไม่ชำรุด ประทับใจมากครับ",
    published_at: "2026-09-07T09:15:00Z",
    masked_order_number: "POD-****-3156",
    masked_customer_name: "ฟลุค",
    verification_status: "delivered",
    items: [{ product_name: "M BAR 10K", flavor_name: "Cola", brand_name: "M BAR" }],
  },
  {
    id: "3",
    rating: 4,
    category: "service",
    review_text: "ระบบใช้งานง่าย ชำระเงินสะดวก แต่หวังว่าจะมีสินค้าเพิ่มเติมในอนาคต",
    published_at: "2026-09-06T16:45:00Z",
    masked_order_number: "POD-****-9024",
    masked_customer_name: "มิ้นท์ เอ.",
    verification_status: "payment_confirmed",
    items: [{ product_name: "VPLUS 16K", flavor_name: "Watermelon", brand_name: "VPLUS" }],
  },
  {
    id: "4",
    rating: 5,
    category: "overall",
    review_text: "บริการดีมาก ติดตามออเดอร์ได้ชัดเจน สินค้าคุณภาพเยี่ยม จะซื้อซ้ำแน่นอน",
    published_at: "2026-09-05T11:20:00Z",
    masked_order_number: "POD-****-4532",
    masked_customer_name: "ณัฐพล ก.",
    verification_status: "delivered",
    items: [
      { product_name: "MOOOD Monster Series 14K", flavor_name: "Kyoho Grape", brand_name: "MOOOD" },
    ],
  },
  {
    id: "5",
    rating: 5,
    category: "product",
    review_text: "รส Mint สดชื่นมาก ไม่แสบคอ ดึงได้ลื่น คุ้มค่ามากๆ",
    published_at: "2026-09-04T18:30:00Z",
    masked_order_number: "POD-****-8871",
    masked_customer_name: "ปีโป้",
    verification_status: "shipped",
    items: [{ product_name: "RELX Pod Pro 2", flavor_name: "Mint Freeze", brand_name: "RELX" }],
  },
  {
    id: "6",
    rating: 4,
    category: "delivery",
    review_text: "ได้รับสินค้าตรงเวลา แพ็คกิ่งแน่นหนา แต่ต้องรอนานหน่อยเพราะสั่งช่วงเทศกาล",
    published_at: "2026-09-03T13:00:00Z",
    masked_order_number: "POD-****-2265",
    masked_customer_name: "แนน",
    verification_status: "delivered",
    items: [{ product_name: "ALFA Duo Mesh 20K", flavor_name: "Watermelon Ice", brand_name: "ALFA" }],
  },
  {
    id: "7",
    rating: 5,
    category: "service",
    review_text: "แอดมินตอบไวมาก มีปัญหาอะไรสอบถามแล้วช่วยแก้ไขทันที ขอบคุณค่ะ",
    published_at: "2026-09-02T10:45:00Z",
    masked_order_number: "POD-****-6743",
    masked_customer_name: "เจมส์ น.",
    verification_status: "delivered",
    items: [{ product_name: "M BAR 10K", flavor_name: "Grape", brand_name: "M BAR" }],
  },
  {
    id: "8",
    rating: 5,
    category: "overall",
    review_text: "ร้านนี้ดีที่สุดเลยครับ สินค้าแท้ ราคาดี จัดส่งเร็ว ไม่ต้องหาที่อื่นแล้ว",
    published_at: "2026-09-01T15:20:00Z",
    masked_order_number: "POD-****-5189",
    masked_customer_name: "บอส ว.",
    verification_status: "delivered",
    items: [
      { product_name: "VPLUS 16K", flavor_name: "Double Apple Shisha", brand_name: "VPLUS" },
      { product_name: "VPLUS 16K", flavor_name: "Blueberry", brand_name: "VPLUS" },
    ],
  },
  {
    id: "9",
    rating: 4,
    category: "product",
    review_text: "พอดรสผลไม้หอมมาก แต่ใช้ไปสักพักเริ่มจืดหน่อย อาจต้องเปลี่ยนบ่อยขึ้น",
    published_at: "2026-08-31T08:50:00Z",
    masked_order_number: "POD-****-3342",
    masked_customer_name: "พีท",
    verification_status: "delivered",
    items: [{ product_name: "MARBO M SWITCH 15K", flavor_name: "Blue Ice", brand_name: "MARBO" }],
  },
  {
    id: "10",
    rating: 5,
    category: "delivery",
    review_text: "ส่งถึงมือภายใน 24 ชั่วโมง แพ็คห่อดีมาก มีฟองน้ำป้องกันกระแทก เห็นใจลูกค้ามาก",
    published_at: "2026-08-30T12:10:00Z",
    masked_order_number: "POD-****-7654",
    masked_customer_name: "สมศรี ค.",
    verification_status: "delivered",
    items: [{ product_name: "MOOOD Monster Series 14K", flavor_name: "Blueberry", brand_name: "MOOOD" }],
  },
];

export const mockReviewSummary: ReviewSummary = {
  average_rating: 4.7,
  total_reviews: 10,
  rating_distribution: { 1: 0, 2: 0, 3: 0, 4: 3, 5: 7 },
};

export const mockReviewsPreviewData = {
  reviews: mockReviews,
  summary: mockReviewSummary,
};